# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-23 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workorder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=64)),
                ('applicant_id', models.IntegerField()),
                ('order_type', models.IntegerField()),
                ('bug_id', models.IntegerField(null=True)),
                ('sys_id', models.IntegerField()),
                ('pj_id', models.IntegerField()),
                ('db_id', models.IntegerField(null=True)),
                ('branch', models.CharField(max_length=64)),
                ('auto_deploy', models.IntegerField()),
                ('db_change', models.IntegerField(null=True)),
                ('cf_change', models.IntegerField(null=True)),
                ('detail', models.CharField(max_length=4096)),
                ('rely_project', models.CharField(max_length=128, null=True)),
                ('online_detail', models.CharField(max_length=4096, null=True)),
                ('conf_detail', models.CharField(max_length=4096, null=True)),
                ('effect_detail', models.CharField(max_length=4096, null=True)),
                ('status', models.IntegerField()),
                ('c_t', models.DateTimeField(null=True)),
                ('u_t', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='workorder_auto_deploy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workorder_id', models.IntegerField()),
                ('result', models.IntegerField(null=True)),
                ('log', models.CharField(max_length=4096, null=True)),
                ('c_t', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='workorder_project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=64)),
                ('applicant_id', models.IntegerField()),
                ('order_type', models.IntegerField()),
                ('db_change', models.IntegerField(null=True)),
                ('pj_ids', models.CharField(max_length=128)),
                ('stage_time', models.DateTimeField()),
                ('online_time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('c_t', models.DateTimeField(null=True)),
                ('u_t', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='workorder_sql',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workorder_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('pjt_id', models.IntegerField()),
                ('db_id', models.IntegerField()),
                ('sql_value', models.CharField(max_length=128)),
                ('c_t', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='workorder_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workorder_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('pjt_id', models.CharField(max_length=128)),
                ('auditor', models.IntegerField(null=True)),
                ('status', models.IntegerField()),
                ('c_t', models.DateTimeField(null=True)),
            ],
        ),
    ]
