# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '\u5df2\u62a5\u540d'), (1, '\u672a\u62a5\u540d')], default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='content',
            field=models.TextField(verbose_name='\u54a8\u8be2\u8bfe\u7a0b\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='customerfollowup',
            name='intention',
            field=models.PositiveSmallIntegerField(choices=[(0, '2\u5468\u5185\u62a5\u540d'), (1, '\u4e00\u4e2a\u6708\u5185\u62a5\u540d'), (2, '\u8fd1\u671f\u65e0\u62a5\u540d\u8ba1\u5212'), (3, '\u5df2\u5728\u5176\u4ed6\u673a\u6784\u62a5\u540d'), (4, '\u5df2\u62a5\u540d'), (0, '\u5df2\u62c9\u9ed1')], verbose_name='\u72b6\u6001'),
        ),
    ]
