# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20180425_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '\u83dc\u5355\u8868', 'verbose_name_plural': '\u83dc\u5355\u8868'},
        ),
    ]
