# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180425_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url_name',
            field=models.CharField(default='/crm/', max_length=64),
        ),
    ]
